title: Konstantinos Tsilimparis
url: https://contsili.github.io
img_path: /contsili.github.io/static/assets/docs

# Menu configuration
menu:
  - title: Career
    url: /career/

# author -- index page "about me" section
author:
    name: Konstantinos Tsilimparis
    first_name: Konstantinos
    last_name: Tsilimparis
    avatar: /static/assets/docs/avatar.jpg
    github_username: contsili
    linkedin_id: konstantinos-tsilimparis
    twitter_username: KonTsilimparis
    email: konstantinos.tsilimparis@outlook.com
    #cv: https://github.com/Remi-Gau/CV/raw/master/CV_English.pdf
    desc: I develop computational models for MEG/EEG and contribute to open-source software.

# Ensure you have a baseurl if necessary
baseurl: ""